# Generated by Django 4.2 on 2023-06-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(max_length=8)),
                ('student_name', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('begin_date', models.DateField()),
            ],
        ),
    ]
