# Generated by Django 4.2 on 2023-06-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='student_id',
            field=models.IntegerField(),
        ),
    ]
