# Generated by Django 4.2 on 2023-06-04 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_studentdetails_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='begin_date',
        ),
    ]
