# Generated by Django 4.2 on 2023-06-04 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_studentdetails_begin_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentDetails',
        ),
    ]
