# Generated by Django 4.2 on 2023-06-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='isApproved',
            field=models.BooleanField(default=True),
        ),
    ]
