# Generated by Django 4.2.2 on 2023-06-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_studentdetails_isapproved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='isApproved',
        ),
    ]
