# Generated by Django 4.2.2 on 2023-07-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_remove_studentdetails_isapproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='isApproved',
            field=models.BooleanField(default=True),
        ),
    ]
