# Generated by Django 4.2.2 on 2023-07-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_studentdetails_isapproved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='isApproved',
        ),
    ]
