# Generated by Django 4.2.2 on 2023-07-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_remove_studentdetails_isapproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='studentImages',
            field=models.ImageField(default='default_image.jpg', upload_to='images/'),
        ),
    ]
