# Generated by Django 4.2.2 on 2023-07-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_studentdetails_studentimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='studentImages',
            field=models.ImageField(upload_to='application/static/images/'),
        ),
    ]
