# Generated by Django 4.2.2 on 2023-07-15 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_studentdetails_studentbarcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='studentBarcode',
        ),
    ]
