# Generated by Django 4.2.2 on 2023-07-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_remove_studentdetails_studentbarcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='status',
            field=models.CharField(blank=True, choices=[('Enrolled', 'Enrolled'), ('Withdrawn', 'Withdrawn'), ('on-leave', 'On Leave'), ('Paused', 'Paused'), ('Terminated', 'Terminated'), ('Graduated', 'Graduated')], max_length=20, null=True),
        ),
    ]
