# Generated by Django 4.2.2 on 2023-08-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_studentdetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='card_status',
            field=models.CharField(blank=True, choices=[('Collected', 'Collected'), ('Lost', 'Lost'), ('Renewed', 'Renewed'), ('In-process', 'In-process')], max_length=20, null=True),
        ),
    ]
